config:
  enable:
    swagger-ui-open: true

server:
  port: 8081

debug: false

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1;DatabaseName=TEST_DATABASE
    username: fx
    password: 123456
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  config-location:
    classpath: com/example/dao/**/*Mapper.xml